### PR TITLE
Bluenose Freighter

### PR DESCRIPTION
**Pull request by BobTheTerrible**
Submission of the Bluenose Freighter

### CODE REVIEW

**Comment by BobTheTerrible** [comment]
Im going to reject this myself as my repo wasnt as clean as I though... by a long way....

**Comment by fluffyfreak** [comment]
Ah that's not so bad @BobTheTerrible, I've merged worse :D

**Comment by laarmen** [comment]
You mean you've done worst, too ;-)

Many thanks for caring about the git history!

**Comment by fluffyfreak** [comment]
Yeah that's what I meant! :D

**Comment by BobTheTerrible** [comment]
This push was particularly bad Github etiquette.... Have submitted to the Pioneer repo, lets see if that passes first :)

**Pull request closed without merging**
